# Generated by Django 4.0.6 on 2022-08-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='book_user_favorite_unique'),
        ),
    ]
