# Generated by Django 4.0.6 on 2022-08-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.TextField()),
                ('book_url', models.TextField()),
                ('cover_image', models.TextField()),
                ('author', models.TextField()),
                ('title', models.TextField()),
                ('price', models.TextField()),
                ('description', models.TextField()),
                ('publisher', models.TextField()),
                ('published_date', models.TextField()),
                ('number_of_pages', models.TextField()),
                ('genre', models.TextField()),
            ],
        ),
    ]
